Description: Serverless demo
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 5
    Runtime: nodejs12.x
    MemorySize: 512
    Environment:
      Variables:
        APP_NAME: 'ServerlessDemo'
        EPSAGON_TOKEN: !Ref EpsagonToken
        DISABLE_EPSAGON: !If [isSamLocal, 'true', 'false']

Parameters:
  EpsagonToken:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: '/monitoring/epsagonToken'

Conditions:
  isSamLocal: !Equals [!Ref 'AWS::StackName', '']

Resources:
  DummyDynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: dummyId
          AttributeType: S
      KeySchema:
        - AttributeName: dummyId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: helloWorldHandler.default
      Events:
        HelloWorldEvent:
          Type: Api
          Properties:
            Path: /hello-world
            Method: GET

  SaveDummy:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: saveDummyHandler.default
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DummyDynamoDbTable
      Events:
        HelloWorldEvent:
          Type: Api
          Properties:
            Path: /dummy
            Method: POST
      Environment:
        Variables:
          DUMMY_TABLE: !Ref DummyDynamoDbTable

Outputs:
  Api:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${ServerlessRestApiProdStage}/"